exports.phraseFromUsername = function phraseFromUsername(username) {
  const phrases = [
    `${username} just joined the server - glhf!`,
    `${username} just joined. Everyone, look busy!`,
    `${username} just joined. Can I get a heal?`,
    `${username} joined your party.`,
    `${username} joined. Deploy to main.`,
    `Ermagherd. ${username} is here.`,
    `Welcome, ${username}. Stay awhile and code.`,
    `Welcome, ${username}. We were expecting you ( ͡° ͜ʖ ͡°)`,
    `Welcome, ${username}. We hope you brought pizza rolls.`,
    `Welcome ${username}. What's your favorite framework?`,
    `A wild ${username} appeared.`,
    `Swoooosh. ${username} just landed.`,
    `Brace yourselves. ${username} just joined the server.`,
    `${username} just joined. Hide your bananas.`,
    `${username} just arrived.`,
    `${username} just slid into the server.`,
    `A ${username} has spawned in the server.`,
    `Big ${username} showed up!`,
    `Where’s ${username}? In the server!`,
    `${username} hopped into the server. Kangaroo!!`,
    `${username} just showed up.`,
    `Coder approaching - ${username} has appeared!`,
    `It's a bird! It's a plane! Nevermind, it's ${username}.`,
    `It's ${username}! Praise the sun! \\\\[T]/`,
    `Never gonna give ${username} up. Never gonna let ${username} down.`,
    `Ha! ${username} has joined! You activated my trap card!`,
    `Cheers, love! ${username}'s here!`,
    `Hey! Listen! ${username} has joined!`,
    `We've been expecting you ${username}`,
    `It's dangerous to go alone, take ${username}!`,
    `${username} has joined the server! It's super effective!`,
    `Cheers, love! ${username} is here!`,
    `${username} is here, as the prophecy foretold.`,
    `${username} has arrived. Party's over.`,
    `Ready player ${username}`,
    `${username} is here to chew bubblegum. ${username} is all out of gum.`,
    `Hello. Is it ${username} you're looking for?`,
    `${username} has joined. Stay a while and listen!`,
    `Roses are red, violets are blue, ${username} joined this server with you`,
  ]

  return phrases[Math.floor(Math.random() * phrases.length)]
}
